### ISSUE TITLE
Blur effect not working in Safari

### ISSUE THREAD

**Issue by mervynlee94** [unoforge/agency-landing-page-Astrojs#9]
The blurring shape became square when it is loaded using Safari. It works as expected using Chrome.
Tested on Safari 17. Not sure about older version.

<img width="1727" alt="Screenshot 2023-12-05 at 17 30 40" src="https://github.com/Johnkat-Mj/agency-landing-page-Astrojs/assets/15529103/2158408e-dcbb-4c61-bec4-e257a1de1146">

**Comment by Johnkat-Mj** [comment]
I'm looking for a way to fix this unfortunately I'm on windows and can't test on Safari, no matter I'll find how

**Comment by TechGfx** [comment]
> I'm looking for a way to fix this unfortunately I'm on windows and can't test on Safari, no matter I'll find how

You find a solution?

**Comment by alangardner-dev** [comment]
The issue is a `overflow-hidden` in the parent div. If it is changed to `overflow-auto` it handles the blur effect on Mac based browsers. I tested in Safari, FF, Chrome. I've created a fork and will commit a PR for review. I don't have a Windows machine, so @Johnkat-Mj will have to test it on Windows.

**Comment by Johnkat-Mj** [comment]
Thank you @alangardner-dev , every thing is fine on windows too
